development:
  # Configure available database clients. (required)
  clients:
    default:
      uri: <%=ENV['MLAB_URI']%>
    accounting:
      uri: <%=ENV['ACCOUNTING_MLAB_URI']%>

  # Configure Mongoid specific options. (optional)
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    raise_not_found_error: false

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false

    # Set the Mongoid and Ruby driver log levels when not in a Rails
    # environment. The Mongoid logger will be set to the Rails logger
    # otherwise.(default: :info)
    # log_level: :info
production:
  clients:
      default:
        uri: <%=ENV['MLAB_URI']%>
      accounting:
        uri: <%=ENV['ACCOUNTING_MLAB_URI']%>
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      uri: <%=ENV['MLAB_URI']%>
    accounting:
      uri: <%=ENV['ACCOUNTING_MLAB_URI']%>
  options:
    raise_not_found_error: false
